src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Timestampable\Traits\TimestampableEntity;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface
{
    use TimestampableEntity;

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     * @Assert\NotBlank
     * @Assert\Email(
     *     message = "The email '{{ value }}' is not a valid email."
     * )
     * @Groups("main")
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @Assert\NotBlank
     * @Assert\Length(
     *     min = 6,
     *     max = 4096,
     *     minMessage = "Your password should be at least {{ limit }} characters",
     * )
     */
    private $plainPassword;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $firstname;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $lastname;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $avatar;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isActive;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $lastLogin;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\ApiToken", mappedBy="user", orphanRemoval=true)
     */
    private $apiTokens;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Article", mappedBy="author", fetch="EXTRA_LAZY")
     */
    private $articles;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $accountValidationToken;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $validationTokenCreatedAt;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $resetPasswordToken;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $passwordTokenCreatedAt;

    /**
     * @ORM\Column(type="datetime")
     */
    private $agreedTermsAt;

    /**
     * @ORM\OneToMany(targetEntity=Like::class, mappedBy="user", orphanRemoval=true)
     */
    private $likes;

    /**
     * @ORM\OneToMany(targetEntity=View::class, mappedBy="userLogged")
     */
    private $views;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Url
     */
    private $website;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Url
     */
    private $linkedin;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Url
     */
    private $twitter;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Url
     */
    private $github;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Url
     */
    private $stackOverflow;

    public function __construct()
    {
        $this->apiTokens = new ArrayCollection();
        $this->articles = new ArrayCollection();
        $this->isActive = false;
        $this->likes = new ArrayCollection();
        $this->views = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getPlainPassword(): string
    {
        return (string) $this->plainPassword;
    }

    public function setPlainPassword(string $plainPassword): self
    {
        $this->plainPassword = $plainPassword;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        $this->plainPassword = null;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(?string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(?string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getFullName(): ?string
    {
        return sprintf('%s %s', $this->getFirstname(), $this->getLastname());
    }

    public function getAvatar(): ?string
    {
        return $this->avatar;
    }

    public function setAvatar(?string $avatar): self
    {
        $this->avatar = $avatar;

        return $this;
    }

    public function getIsActive(): ?bool
    {
        return $this->isActive;
    }

    public function setIsActive(bool $isActive): self
    {
        $this->isActive = $isActive;

        return $this;
    }

    public function getLastLogin(): ?\DateTimeInterface
    {
        return $this->lastLogin;
    }

    public function setLastLogin(?\DateTimeInterface $lastLogin): self
    {
        $this->lastLogin = $lastLogin;

        return $this;
    }

    /**
     * @return Collection|ApiToken[]
     */
    public function getApiTokens(): Collection
    {
        return $this->apiTokens;
    }

    public function addApiToken(ApiToken $apiToken): self
    {
        if (!$this->apiTokens->contains($apiToken)) {
            $this->apiTokens[] = $apiToken;
            $apiToken->setUser($this);
        }

        return $this;
    }

    public function removeApiToken(ApiToken $apiToken): self
    {
        if ($this->apiTokens->contains($apiToken)) {
            $this->apiTokens->removeElement($apiToken);
            // set the owning side to null (unless already changed)
            if ($apiToken->getUser() === $this) {
                $apiToken->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Article[]
     */
    public function getArticles(): Collection
    {
        return $this->articles;
    }

    public function addArticle(Article $article): self
    {
        if (!$this->articles->contains($article)) {
            $this->articles[] = $article;
            $article->setAuthor($this);
        }

        return $this;
    }

    public function removeArticle(Article $article): self
    {
        if ($this->articles->contains($article)) {
            $this->articles->removeElement($article);
            // set the owning side to null (unless already changed)
            if ($article->getAuthor() === $this) {
                $article->setAuthor(null);
            }
        }

        return $this;
    }

    public function getAccountValidationToken(): ?string
    {
        return $this->accountValidationToken;
    }

    public function setAccountValidationToken(?string $accountValidationToken): self
    {
        $this->accountValidationToken = $accountValidationToken;

        return $this;
    }

    public function getValidationTokenCreatedAt(): ?\DateTimeInterface
    {
        return $this->validationTokenCreatedAt;
    }

    public function setValidationTokenCreatedAt(?\DateTimeInterface $validationTokenCreatedAt): self
    {
        $this->validationTokenCreatedAt = $validationTokenCreatedAt;

        return $this;
    }

    public function getResetPasswordToken(): ?string
    {
        return $this->resetPasswordToken;
    }

    public function setResetPasswordToken(?string $resetPasswordToken): self
    {
        $this->resetPasswordToken = $resetPasswordToken;

        return $this;
    }

    public function getPasswordTokenCreatedAt(): ?\DateTimeInterface
    {
        return $this->passwordTokenCreatedAt;
    }

    public function setPasswordTokenCreatedAt(?\DateTimeInterface $passwordTokenCreatedAt): self
    {
        $this->passwordTokenCreatedAt = $passwordTokenCreatedAt;

        return $this;
    }

    public function getAgreedTermsAt(): ?\DateTimeInterface
    {
        return $this->agreedTermsAt;
    }

    public function setAgreedTermsAt(?\DateTimeInterface $agreedTermsAt): self
    {
        $this->agreedTermsAt = $agreedTermsAt;

        return $this;
    }

    public function agreeTerms()
    {
        $this->agreedTermsAt = new \DateTime();
    }

    /**
     * @return Collection|Like[]
     */

src/Controller/AccountController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\UserForgottenType;
use App\Form\UserPasswordResetType;
use App\Form\UserPasswordUpdateType;
use App\Form\UserUpdateType;
use App\Model\ChangePassword;
use App\Repository\UserRepository;
use App\Utils\DelayTokenVerificator;
use App\Utils\Mailer;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;
use Symfony\Component\Security\Csrf\TokenGenerator\TokenGeneratorInterface;

/**
 * @Route("/account")
 */
class AccountController extends AbstractController
{
    /**
     * @Route("/", name="web_account_index")
     */
    public function show()
    {
        return $this->render('account/index.html.twig', [
            'user' => $this->getUser(),
        ]);
    }

    /**
     * @Route("/{id}/edit", name="web_account_edit", methods={"GET","POST"}, requirements={"id"="\d+"})
     */
    public function edit(Request $request, User $user = null)
    {
        if(!$user) {
            throw $this->createNotFoundException('User introuvable');
        }

        if($this->getUser() === $user) {
            $form = $this->createForm(UserUpdateType::class, $user);
            $form->handleRequest($request);

            if ($form->isSubmitted() && $form->isValid()) {
                $entityManager = $this->getDoctrine()->getManager();
                $entityManager->flush();

                return $this->redirectToRoute('web_account_index');
                    //$this->redirectToRoute('user_show', ['slug' => $user->getSlug()]);
            }

            return $this->render('account/edit.html.twig', [
                'user' => $user,
                'form' => $form->createView(),
            ]);
        }
        return $this->redirectToRoute('web_account_index');
            //$this->redirectToRoute('user_show', ['slug'=>$user->getSlug()]);
    }

    /**
     * @Route("/{id}/edit-password", name="web_account_edit-password", methods={"GET","POST"}, requirements={"id"="\d+"})
     */
    public function updatePassword(Request $request, User $user = null, UserPasswordEncoderInterface $passwordEncoder)
    {
        if(!$user) {
            throw $this->createNotFoundException('User introuvable');
        }

        if($this->getUser() === $user) {
            $changePassword = new ChangePassword();
            $form = $this->createForm(UserPasswordUpdateType::class, $changePassword);
            $form->handleRequest($request);

            if ($form->isSubmitted() && $form->isValid()) {
                $newPassword = $form->get('password')['first']->getData();
                $newEncodedPassword = $passwordEncoder->encodePassword($user, $newPassword);

                $user->setPassword($newEncodedPassword);

                $entityManager = $this->getDoctrine()->getManager();
                $entityManager->flush();

                return $this->redirectToRoute('web_account_index');
            }

            return $this->render('account/edit.html.twig', [
                'user' => $user,
                'form' => $form->createView(),
            ]);
        }
        return $this->redirectToRoute('web_account_index');
    }

    /**
     * @Route("/api/account", name="api_account")
     */
    public function accountApi()
    {
        $user = $this->getUser();

        return $this->json($user, 200, [], [
            'groups' => ['main'],
        ]);
    }

    /**
     * @Route("/forgotten-password", name="app_forgotten-password", methods={"GET","POST"})
     */
    public function forgottenPassword(Request $request, UserRepository $userRepository, TokenGeneratorInterface $tokenGenerator, Mailer $mailer)
    {
        $form = $this->createForm(UserForgottenType::class);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $email = $form->get('email')->getData();

            $user = $userRepository->findOneBy([
                'email' => $email,
            ]);

            if(!$user) {
                $this->addFlash(
                    'danger',
                    'Email Inconnu'
                );
                return $this->redirectToRoute('app_forgotten-password');
            }

            $token = $tokenGenerator->generateToken();
            $user->setResetPasswordToken($token);
            $user->setPasswordRequestedAt(new \DateTime());

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->flush();

            $this->addFlash(
                'success',
                'Demande de réinitialisation du mot de passe effectué avec succès'
            );

            $body = 'email/account-recovery.html.twig';
            $context = [
                'user' => $user
            ];
            $mailer->sendMessage('from@email.com', $user->getEmail(), 'Account Recovery', $body, $context);

            $this->addFlash(
                'success',
                'Un mail de réinitialisation a été envoyé à l\'adresse '.$user->getEmail()
            );

            return $this->redirectToRoute('app_login');
        }
        return $this->render('account/forgotten-password.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/reset-password/{resetPasswordToken}", name="app_reset-password", methods={"GET","POST"})
     */
    public function resetPassword(Request $request, User $user = null, UserPasswordEncoderInterface $passwordEncoder, DelayTokenVerificator $tokenVerificator)
    {
        if(!$user || $tokenVerificator->isValidToken($user->getPasswordRequestedAt()) === false) {
            $this->addFlash(
                'danger',
                'Expired token'
            );
            return $this->redirectToRoute('app_forgotten-password');
        }

        $form = $this->createForm(UserPasswordResetType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $password = $passwordEncoder->encodePassword($user, $user->getPassword());
            $user->setPassword($password);
            $user->setResetPasswordToken(null);
            $user->setPasswordRequestedAt(null);
            $this->getDoctrine()->getManager()->flush();

            $this->addFlash(
                'success',
                'Mot de passe modifié avec succès'
            );

            return $this->redirectToRoute('app_login');
        }
        return $this->render('account/reset-password.html.twig', [
            'form' => $form->createView(),
        ]);
    }
}

templates/web/account/account-base.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="post">
        <h1>{% block account_title %}

            {% endblock %}
        </h1>
        {% if user is defined and user is not null %}
        <div class="row">
            <div class="col-md-3">
                {% if is_granted('IS_AUTHENTICATED_FULLY') and app.user.id == user.id %}
                <div class="list-group mb-2">
                    <a href="{{ path('web_account_index', {'id':user.id}) }}" class="list-group-item list-group-item-action"><i class="fas fa-house-user"></i> <span>Account home</span></a>
                    <a href="{{ path('web_account_edit', {'id':user.id}) }}" class="list-group-item list-group-item-action"><i class="fas fa-user-edit"></i> <span>Edit Information</span></a>
                    <a href="{{ path('web_account_edit-password', {'id':user.id}) }}" class="list-group-item list-group-item-action"><i class="fas fa-edit"></i> <span>Edit Password</span></a>
                </div>
                {% endif %}
            </div>
            <div class="mt-sm-2 mt-md-0 col-md-9">
                <div class="card">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-12">
                                {% block account_content %}

                                {% endblock %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% else %}
            <p>No record found</p>
        {% endif %}
    </div>
{% endblock %}

templates/web/account/edit-password.html.twig
{% extends 'web/account/account-base.html.twig' %}

{% block title %}
    Edit Account!
    {{ parent() }}
{% endblock %}

{% block account_title %}
    Edit Account!
{% endblock %}

{% block account_content %}
    {{ form_start(form) }}
    <fieldset>
    <legend>Password</legend>
        <div class="form-group">
            {{ form_label(form.oldPassword) }}
            <div class="input-group">
                <div class="input-group-prepend">
                    <span class="input-group-text" id="inputGroupPrependName"><i class="fas fa-lock"></i></span>
                </div>
                {{ form_widget(form.oldPassword) }}
            </div>
        </div>
        <div class="form-group">
            {{ form_label(form.password.first) }}
            <div class="input-group">
                <div class="input-group-prepend">
                    <span class="input-group-text" id="inputGroupPrependName"><i class="fas fa-lock"></i></span>
                </div>
                {{ form_widget(form.password.first) }}
            </div>
        </div>
        <div class="form-group">
            {{ form_label(form.password.second) }}
            <div class="input-group">
                <div class="input-group-prepend">
                    <span class="input-group-text" id="inputGroupPrependName"><i class="fas fa-lock"></i></span>
                </div>
                {{ form_widget(form.password.second) }}
            </div>
        </div>
    </fieldset>
    <button class="btn btn-primary">{{ button_label|default('Save') }}</button>
    {{ form_end(form) }}
{% endblock %}

templates/web/account/edit.html.twig
{% extends 'web/account/account-base.html.twig' %}

{% block title %}
    Edit Account!
    {{ parent() }}
{% endblock %}

{% block account_title %}
    Edit Account!
{% endblock %}

{% block account_content %}
    {{ form_start(form) }}
    <fieldset>
    <legend>General information</legend>
    <div class="row mx-auto">
        <div class="image-container">
            <img class="account-image" src="{{ user.avatar }}">
            <div class="content-overlay">
                <div class="content">
                    <a href="#"><i class="far fa-edit"></i></a>
                </div>
            </div>
        </div>
    </div>
    <div class="form-group">
        {{ form_label(form.email) }}
        <div class="input-group">
            <div class="input-group-prepend">
                <span class="input-group-text" id="inputGroupPrependName"><i class="fas fa-at"></i></span>
            </div>
            {{ form_widget(form.email) }}
        </div>
    </div>
    <div class="form-group">
        {{ form_label(form.firstname) }}
        <div class="input-group">
            <div class="input-group-prepend">
                <span class="input-group-text" id="inputGroupPrependName"><i class="far fa-id-card"></i></span>
            </div>
            {{ form_widget(form.firstname) }}
        </div>
    </div>
    <div class="form-group">
        {{ form_label(form.lastname) }}
        <div class="input-group">
            <div class="input-group-prepend">
                <span class="input-group-text" id="inputGroupPrependName"><i class="far fa-id-card"></i></span>
            </div>
            {{ form_widget(form.lastname) }}
        </div>
    </div>
    </fieldset>
    <fieldset>
    <legend>Social media</legend>
    <div class="form-group">
        {{ form_label(form.website) }}
        <div class="input-group">
            <div class="input-group-prepend">
                <span class="input-group-text" id="inputGroupPrependName"><i class="fas fa-globe-europe"></i></span>
            </div>
            {{ form_widget(form.website) }}
        </div>
    </div>
    <div class="form-group">
        {{ form_label(form.linkedin) }}
        <div class="input-group">
            <div class="input-group-prepend">
                <span class="input-group-text" id="inputGroupPrependName"><i class="fab fa-linkedin-in"></i></span>
            </div>
            {{ form_widget(form.linkedin) }}
        </div>
    </div>
    <div class="form-group">
        {{ form_label(form.twitter) }}
        <div class="input-group">
            <div class="input-group-prepend">
                <span class="input-group-text" id="inputGroupPrependName"><i class="fab fa-twitter"></i></span>
            </div>
            {{ form_widget(form.twitter) }}
        </div>
    </div>
    <div class="form-group">
        {{ form_label(form.github) }}
        <div class="input-group">
            <div class="input-group-prepend">
                <span class="input-group-text" id="inputGroupPrependName"><i class="fab fa-github"></i></span>
            </div>
            {{ form_widget(form.github) }}
        </div>
    </div>
    <div class="form-group">
        {{ form_label(form.stackOverflow) }}
        <div class="input-group">
            <div class="input-group-prepend">
                <span class="input-group-text" id="inputGroupPrependName"><i class="fab fa-stack-overflow"></i></span>
            </div>
            {{ form_widget(form.stackOverflow) }}
        </div>
    </div>
    </fieldset>
    <button class="btn btn-primary">{{ button_label|default('Save') }}</button>
    {{ form_end(form) }}
{% endblock %}

templates/web/account/forgotten-password.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Forgotten password!
    {{ parent() }}
{% endblock %}

{% block body %}
    <div class="post">
        <h1>Forgotten password ?</h1>
        {{ form_start(form) }}
        {{ form_widget(form) }}
        <button class="btn btn-primary">{{ button_label|default('Send email') }}</button>
        {{ form_end(form) }}
    </div
{% endblock %}

templates/web/account/index.html.twig
{% extends 'web/account/account-base.html.twig' %}

{% block title %}
    {% if user.fullName is not null %}
       {{ user.fullName }}
    {% else %}
        {{ user.email }}
    {% endif %}
    profile's !
    {{ parent() }}
{% endblock %}

{% block account_title %}
    {% if user.firstname is null and user.lastname is null %}
        {{ user.email }}
    {% else %}
        {{ user.fullName }}
    {% endif %}
    profile's
{% endblock %}

{% block account_content %}
    <div>
        <h2>General</h2>
        <div class="row mx-auto">
            <div class="image-container">
                <img class="account-image" src="{{ user.avatar }}">
            </div>
        </div>
        <p>Username : <span>{{ user.username }}</span></p>
        <p>Email : <span>{{ user.email }}</span></p>
        <p>Firstname : <span>{{ user.firstname }}</span></p>
        <p>Lastname : <span>{{ user.lastname }}</span></p>
        <p>Website : <span>{{ user.website }}</span></p>
        <p>Linkedin : <span>{{ user.linkedin }}</span></p>
        <p>Twitter : <span>{{ user.twitter }}</span></p>
        <p>Github : <span>{{ user.github }}</span></p>
        <p>StackOverflow : <span>{{ user.stackOverflow }}</span></p>
    </div>
    <div>
        <h2>Content management</h2>
        <h4>Articles</h4>
        <ul>
        {% for article in user.articles %}
           <li><a href="{{ path('web_articles_show', {'slug':article.slug}) }}">{{ article.title }}</a></li>
        {% else %}
            <p>No content</p>
        {% endfor %}
        </ul>
    </div>
    <div>
        <h2></h2>
        <h4>Likes</h4>
        <ul>
            {% for like in user.likes %}
                <li><a href="{{ path('web_articles_show', {'slug':like.article.slug}) }}">{{ like.article.title }}</a></li>
            {% else %}
                <p>No content</p>
            {% endfor %}
        </ul>
    </div>
    <div>
        <h4>Views</h4>
        <ul>
            {% for view in user.views %}
                <li><a href="{{ path('web_articles_show', {'slug':view.article.slug}) }}">{{ view.article.title }}</a></li>
            {% else %}
                <p>No content</p>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

templates/web/account/reset-password.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Reset password!
    {{ parent() }}
{% endblock %}

{% block body %}
    <div class="post">
        <h1>Reset password </h1>
        {{ form_start(form) }}
        {{ form_widget(form) }}
        <button class="btn btn-primary">{{ button_label|default('Reset') }}</button>
        {{ form_end(form) }}
    </div
{% endblock %}